[[redirects]]
  from = "https://selftaught-dev.com/resume-template/"
  to = "https://courses.selftaught-dev.com/course/self-taught-dev-resume-template"
  status = 301
  force = true

  from = "https://selftaught-dev.com/portfolio/"
  to = "https://portfolio.selftaught-dev.com/"
  status = 301
  force = true